### 1. 尝试直接“翻墙”访问滑板车列表 (没带证件)
GET http://localhost:8080/api/scooters

### 2. 领token
POST http://localhost:8080/api/users/login?username=admin&password=123456

> {%
    client.global.set("auth_token", response.body.token);
    client.log("领到证件啦！Token: " + response.body.token);
%}

### 3. 佩戴token再次进入
GET http://localhost:8080/api/scooters
Authorization: {{auth_token}}

### 4. 带个错误的 Token试试
# 预期结果：被保安识破，返回 401
GET http://localhost:8080/api/scooters
Authorization: ThisIsAFakeToken123456