# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123123
          MYSQL_DATABASE: scooter_sharing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    
    - name: Verify config file in JAR
      run: |
        unzip -l target/ScooterRentalSystem-1.0-SNAPSHOT.jar | grep application.properties

    - name: Start Spring Boot Application
      run: |
       nohup java -jar target/ScooterRentalSystem-1.0-SNAPSHOT.jar > app.log 2>&1 &
        until nc -z localhost 8080; do
          echo "Waiting for Spring Boot to start..."
          sleep 10
        done
        echo "Spring Boot started successfully!"

    - name: Show SpringBoot Log
      run: cat app.log

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install pytest requests
      run: |
        python -m pip install --upgrade pip
        pip install pytest requests pytest-html pytest-md

    - name: Run pytest API Tests
      run: |
        TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
         python test/test_run_all_api.py 2>&1 | tee test/reports_md/API测试报告_${TIMESTAMP}.md

    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-build
        path: target/*.jar
